### ISSUE TITLE
Implement the Spiteful Ghost

### ISSUE THREAD

**Issue by hjwylde** [hjwylde/werewolf#206]
The Spiteful Ghost is a loner that starts off dead. They know everyone's roles and cannot win, but may reck havoc with their knowledge.

**Comment by davismatt1** [comment]
Lore: In a town as diverse as Fougères, it would seem unlikely the villagers would unanimously agree on something. However every villager would agree the town is haunted. This is because the Spiteful Ghost is just so spiteful about their death, they are haunting the town - ensuring the upset town is aware of their presence. Although the Spiteful ghost is dead and cannot win, they do know all the role allocations for the game and may haunt the town as they wish.

**Comment by hjwylde** [comment]
+1 thank you !!
